# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

context:
  name: hydra-python
  version: "0.10.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/CategoricalData/hydra/archive/refs/tags/${{ version }}.tar.gz
  sha256: "0000000000000000000000000000000000000000000000000000000000000000"

build:
  number: 0
  noarch: python
  script:
    interpreter: nushell
    content: |
      # Build the Python package using pip
      cd $env.SRC_DIR/hydra-python

      # Install the package using pip
      python -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

      # Copy license and documentation
      if ("README.md" | path exists) { cp README.md $env.PREFIX }

requirements:
  build:
    - python >=3.12
    - pip
    - hatchling
  host:
    - python >=3.12
    - pip
    - hatchling
  run:
    - python >=3.12

tests:
  - python:
      imports:
        - hydra
  - script:
      - python -c "import hydra; print('Hydra Python imported successfully')"

about:
  homepage: https://github.com/CategoricalData/hydra
  license: Apache-2.0
  license_file: LICENSE
  summary: Hydra Python implementation - type-safe transformations for data and programs
  description: |
    Hydra is a domain-specific language for data models and data transformations.
    It is based on a typed lambda calculus, and transforms data and schemas between
    languages in a way which maintains type conformance. This package contains the
    Python implementation of Hydra (in progress).
  repository: https://github.com/CategoricalData/hydra
  documentation: https://github.com/CategoricalData/hydra/tree/main/hydra-python

extra:
  recipe-maintainers:
    - joshsh
    - phreed
