context:
  name: bitwarden-cli
  version: "2025.10.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/bitwarden/clients/archive/refs/tags/cli-v${{ version }}.tar.gz
  sha256: e9f5b989e3403525c08ef0d295e7a315de2e5f05121e67b0352fed21417277df
  file_name: bitwarden-cli-${{ version }}.tgz

build:
  number: 0
  script:
    - npm install -g bitwarden-cli-${{ version }}.tgz --prefix ${{ PREFIX }}
    # - find ${{ PREFIX }} -type f -executable -exec chmod +x {} \;

requirements:
  host:
    - nodejs
    - pnpm
    - webpack-cli
    - crossenv
  run:
    - nodejs

tests:
  # - package_contents:
  #     bin:
  #       - bw
  # - script:
  #     - bw --version

about:
  homepage: https://bitwarden.com/help/cli/
  license: GPL-3.0-only
  summary: "A secure and free password manager for all of your devices."
  documentation: https://bitwarden.com/help/cli/
  repository: https://github.com/bitwarden/clients/tree/main/apps/cli

extra:
  recipe-maintainers:
    - phreed
