context:
  name: bitwarden-cli
  version: "2025.10.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@bitwarden/cli/-/cli-${{ version }}.tgz
  sha256: 4a1055bb01a3ea9eabb0b437c0bf6a228b924886fc77407fff48503c1457b403 # TODO: Update with correct SHA256 hash

build:
  number: 0
  script:
    # Extract the package
    - tar -xzf cli-${{ version }}.tgz
    - cd package
    # Install dependencies for license generation
    - pnpm install --prod
    # Generate license files
    - mkdir -p ${{ PREFIX }}/share/licenses/${{ name }}
    - npx @quantco/pnpm-licenses list --prod --json --output-file ${{ PREFIX }}/share/licenses/${{ name }}/licenses.json
    - npx @quantco/pnpm-licenses generate-disclaimer --prod --output-file ${{ PREFIX }}/share/licenses/${{ name }}/THIRD_PARTY_LICENSES.txt
    # Install the CLI globally using pnpm
    - pnpm install -g . --prefix ${{ PREFIX }}

requirements:
  host:
    - nodejs
    - pnpm
    - npm
  run:
    - nodejs

tests:
  commands:
    - bw --version
    - bw --help

about:
  homepage: https://bitwarden.com/help/cli/
  license: GPL-3.0-only
  summary: "A secure and free password manager for all of your devices."
  documentation: https://bitwarden.com/help/cli/
  repository: https://github.com/bitwarden/clients/tree/main/apps/cli

extra:
  recipe-maintainers:
    - phreed
