
context:
  name: 'oracle-jdk'
  version: 8.0.321

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: './src'

build:
  number: 0

requirements:
  build: []
  host: []
  run: []

test:
  commands:
    - sel(linux):
        - test -d ${PREFIX}/foo
    - sel(win):
        - if not exist %PREFIX%\foo

#outputs:
#  - name: '{{ name }}'
#    - sel(linux): []
#    - sel(win): []

about:
  home: https://github.com/babeloff/oracle_jdk_boa
  license: MIT
  summary: 'Meta-package for Oracle JDK'
  description: |
    This module provides a meta installer for the Oracle JDK.
    It expects the appropriate Oracle JDK to have been previously acquired.
    It may be acquired from https://www.oracle.com/java/technologies/downloads/#java8-windows
  dev_url: https://github.com/babeloff/oracle_jdk_boa
  doc_url: https://github.com/babeloff/oracle_jdk_boa

extra:
  recipe-maintainers:
    - 'Fred Eisele'
