# Recipe for asciidoctor-revealjs Ruby gem
# A reveal.js converter for Asciidoctor and Asciidoctor.js that transforms an AsciiDoc document into an HTML5 presentation

context:
  name: asciidoctor-revealjs
  version: "5.2.0"

package:
  name: rb-${{ name|lower }}
  version: ${{ version }}

source:
  url: https://rubygems.org/downloads/${{ name }}-${{ version }}.gem
  sha256: 3504a5e7eaf2c91de37f96189314ffb1e6bf94dad9d646d5c9a24c6691bf6ae2

build:
  noarch: generic
  number: 0
  script: |
    gem install --no-document --ignore-dependencies --install-dir ${{ PREFIX }}/lib/ruby/gems ${{ name }}-${{ version }}.gem

requirements:
  build:
    - ruby
  host:
    - ruby
  run:
    - ruby >=2.7
    - asciidoctor >=2.0.0,<3.0.0

tests:
  - script:
      - nu test-pkg.nu --debug
    requirements:
      run:
        - nushell
        - ruby
    files:
      recipe:
        - test-pkg.nu

about:
  homepage: https://github.com/asciidoctor/asciidoctor-reveal.js
  summary: A reveal.js converter for Asciidoctor. Write your slides in AsciiDoc!
  description: |
    Asciidoctor reveal.js is a converter for Asciidoctor and Asciidoctor.js that
    transforms an AsciiDoc document into an HTML5 presentation designed to be
    executed by the reveal.js presentation framework.
  license: MIT
  documentation: https://docs.asciidoctor.org/reveal.js-converter/latest/
  repository: https://github.com/asciidoctor/asciidoctor-reveal.js

extra:
  recipe-maintainers:
    - conda-forge/ruby
