schema_version: 1

context:
  name: ghc2
  version: "9.4.8"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

# No source section needed since we're using ghcup to install GHC

build:
  number: 0
  script: build.nu

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - nushell
    - ghcup
    - make
    - perl
    - if: linux
      then: patchelf
  host:
    - gmp
    - ncurses
    - libffi
  run:
    - ${{ c_compiler }}_${{ target_platform }} >=${{ c_compiler_version }}
    - gmp
    - ncurses
    - libffi

tests:
  - script: test.nu --debug
    files:
      recipe:
        - test.nu
    requirements:
      build:
        - nushell
        - ${{ compiler('c') }}

about:
  homepage: https://haskell.org/ghc/
  license: BSD-3-Clause
  license_file:
    - LICENSE.txt
  summary: Glorious Glasgow Haskell Compilation System (installed via ghcup)
  description: |
    The Glasgow Haskell Compiler (GHC) is a state-of-the-art, open source,
    compiler and interactive environment for the functional language Haskell.
    This package uses ghcup to install GHC, providing a more streamlined
    and consistent installation process across platforms.
  documentation: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/
  repository: https://github.com/ghc/ghc

extra:
  recipe-maintainers:
    # - eggzilla
    # - step21
    # - xhochy
    - phreed
