# Recipe for asciidoctor-diagram Ruby gem
# A family of Asciidoctor extensions that generate images from a broad range of embedded plain text diagram descriptions

context:
  name: asciidoctor-diagram
  version: "3.0.1"

package:
  name: rb-${{ name|lower }}
  version: ${{ version }}

source:
  url: https://rubygems.org/downloads/${{ name }}-${{ version }}.gem
  sha256: a91bde8ef01b0c1c114ca5404b9c3b95ae930980167ffd477d49150cf610f4a4

build:
  noarch: generic
  number: 0
  script: |
    gem install --no-document --ignore-dependencies --install-dir ${{ PREFIX }}/lib/ruby/gems ${{ name }}-${{ version }}.gem

requirements:
  build:
    - ruby
  host:
    - ruby
  run:
    - ruby >=2.7
    - asciidoctor >=1.5.7,<3.0
    - rb-rexml

tests:
  - script:
      - nu test-pkg.nu --debug
    requirements:
      run:
        - nushell
        - ruby
    files:
      recipe:
        - test-pkg.nu
        - test-diagram.adoc
        - class-diagram.puml

about:
  homepage: https://github.com/asciidoctor/asciidoctor-diagram
  summary: Asciidoctor diagramming extension
  description: |
    A family of Asciidoctor extensions that generate images from a broad range of
    embedded plain text diagram descriptions, including PlantUML, ditaa, Kroki,
    and many others. The extension supports AsciiToSVG, BlockDiag (BlockDiag,
    SeqDiag, ActDiag, NwDiag), Ditaa, Erd, GraphViz, Mermaid, Msc, PlantUML,
    Shaape, SvgBob, Syntrax, UMLet, Vega, Vega-Lite and WaveDrom.
  license: MIT
  documentation: https://docs.asciidoctor.org/diagram-extension/latest/
  repository: https://github.com/asciidoctor/asciidoctor-diagram

extra:
  recipe-maintainers:
    - conda-forge/ruby
