# Recipe for asciidoctor-diagram Ruby gem
# A family of Asciidoctor extensions that generate images from a broad range of embedded plain text diagram descriptions

context:
  name: asciidoctor-diagram
  version: "3.0.1"

package:
  name: rb-${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/asciidoctor/asciidoctor-diagram/archive/v${{ version }}.tar.gz
  sha256: 3dd31c3b0d7ff534767a66a7ef3ff9217220623fb82695ebbc8573a99e109941

build:
  noarch: generic
  number: 0
  script: |
    gem build ${{ name }}.gemspec
    gem install --no-document --ignore-dependencies --install-dir ${{ PREFIX }}/lib/ruby/gems ${{ name }}-${{ version }}.gem

requirements:
  build:
    - ruby
  host:
    - ruby
  run:
    - ruby >=2.7
    - asciidoctor >=1.5.7,<3.0
    - rb-rexml

tests:
  - script:
      - nu test-pkg.nu --debug
    requirements:
      run:
        - nushell
        - ruby
    files:
      recipe:
        - test-pkg.nu

about:
  homepage: https://github.com/asciidoctor/asciidoctor-diagram
  summary: Asciidoctor diagramming extension
  description: |
    A family of Asciidoctor extensions that generate images from a broad range of
    embedded plain text diagram descriptions, including PlantUML, ditaa, Kroki,
    and many others. The extension supports AsciiToSVG, BlockDiag (BlockDiag,
    SeqDiag, ActDiag, NwDiag), Ditaa, Erd, GraphViz, Mermaid, Msc, PlantUML,
    Shaape, SvgBob, Syntrax, UMLet, Vega, Vega-Lite and WaveDrom.
  license: MIT
  license_file: LICENSE.txt
  documentation: https://docs.asciidoctor.org/diagram-extension/latest/
  repository: https://github.com/asciidoctor/asciidoctor-diagram

extra:
  recipe-maintainers:
    - conda-forge/ruby
